default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # Linting
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # Git tidy
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      # Security
      - id: detect-private-key
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, update, chore, test]
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.14.6
    hooks:
      - id: ansible-lint
        exclude: ^(\.github/|docs/|changelogs/)
  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 0.22.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
