---
- name: Reset SSH connection prior testing the OCI_CLI_AUTH env var
  ansible.builtin.meta: reset_connection

- name: Refresh facts in order to get the newly added variable
  ansible.builtin.setup:

- name: Fail if the OCI_CLI_AUTH env var is not set
  ansible.builtin.fail:
    msg: "The OCI_CLI_AUTH var is not set. Check your profile"
  when: ansible_env.OCI_CLI_AUTH != 'instance_principal'

- name: Issue a test OCI cli command
  changed_when: false
  ansible.builtin.command:
    cmd: oci os ns get
  register: test_oci_cli_command

- name: "[DEBUG] Show the output of the test command"
  ansible.builtin.debug:
    var: test_oci_cli_command
    verbosity: 1
