---
- name: "[META] Set the NodeInitStatus as starting"
  oracle.oci.oci_compute_instance:
    instance_id: "{{ oracle_metadata_instance.id }}"
    auth_type: instance_principal
    defined_tags:
      K3s-NodeInfo:
        NodeInitStatus: starting

- name: Install the required packages (via apt)
  become: true
  tags:
    - system
    - install
  ansible.builtin.import_tasks: packages_install_deb.yml
  when: ansible_facts['os_family'] | lower == 'debian'

- name: Install additional distro-independent packages
  become: true
  tags:
    - system
    - install
  ansible.builtin.import_tasks: packages_install.yml

- name: Configure packages
  become: true
  tags:
    - system
    - config
  ansible.builtin.import_tasks: packages_config.yml
