---
- name: "[K3s] Download and install the binary and set up the systemd unit"
  tags:
    - k3s
    - setup
  become: true
  ansible.builtin.import_tasks: k3s_download_install.yml

- name: "[META] [MASTER] Set the NodeInitStatus as configuring"
  oracle.oci.oci_compute_instance:
    instance_id: "{{ oracle_metadata_instance.id }}"
    auth_type: instance_principal
    defined_tags:
      K3s-NodeInfo:
        NodeInitStatus: configuring

- name: "[K3s] Generate the common config"
  tags:
    - k3s
    - config
  become: true
  ansible.builtin.import_tasks: k3s_config.yml

- name: "[K3s] Generate the masters config"
  tags:
    - k3s
    - config
    - masters
  become: true
  ansible.builtin.import_tasks: k3s_config_masters.yml
  when: oracle_metadata_instance.definedTags["K3s-NodeInfo"].NodeRole == "master"

- name: "[K3s] Generate the workers config"
  tags:
    - k3s
    - config
    - workers
  become: true
  ansible.builtin.import_tasks: k3s_config_workers.yml
  when: oracle_metadata_instance.definedTags["K3s-NodeInfo"].NodeRole == "worker"
