- name: Download K3s
  ansible.builtin.get_url:
    url: "{{ k3s_release_data.json.assets | selectattr('name', 'match', '^k3s-' + sanitize_arch[lookup('ansible.builtin.vars', 'ansible_machine')] + '$') | map(attribute='browser_download_url') | first }}"
    dest: /usr/local/bin/k3s
    mode: "0755"
    owner: root
    group: root
    checksum: "sha256:{{ k3s_release_data.json.assets | selectattr('name', 'match', '^sha256sum-' + sanitize_arch[lookup('ansible.builtin.vars', 'ansible_machine')] + '\\.txt$') | map(attribute='browser_download_url') | first }}"

- name: Setup K3s systemd unit
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/k3s-io/k3s/{{ k3s_version | urlencode }}/k3s.service"
    dest: /etc/systemd/system/k3s.service
    mode: "0755"
    owner: root
    group: root
  notify:
    - Systemd reload
