---
# https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/gettingmetadata.htm
- name: Get this instance metadata
  ansible.builtin.uri:
    url: "http://169.254.169.254/opc/v2/{{ item }}"
    method: GET
    headers:
      Authorization: Bearer Oracle
  register: opc_v2_metadata
  with_items:
    - instance
    - vnics
    # - volumeAttachments

- name: "[DEBUG] Check the instance details"
  ansible.builtin.debug:
    msg: "{{ opc_v2_metadata.results }}"
    verbosity: 1

- name: Set instance metadata as facts
  ansible.builtin.set_fact:
    oracle_metadata_instance: "{{ opc_v2_metadata.results | selectattr('item','equalto','instance') | map(attribute='json') | first }}"
    oracle_metadata_vnic: "{{ opc_v2_metadata.results | selectattr('item','equalto','vnics') | map(attribute='json') | first }}"

- name: "[DEBUG] Check facts are set"
  ansible.builtin.debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - oracle_metadata_instance
    - oracle_metadata_vnic

- name: Fetch facts about this instance
  oracle.oci.oci_compute_instance_facts:
    instance_id: "{{ oracle_metadata_instance.id }}"
    auth_type: instance_principal
  register: oci_compute_facts

- name: "[DEBUG] Print all available OCI facts"
  ansible.builtin.debug:
    var: oci_compute_facts
    verbosity: 1

- name: "Fetch metadata for K3s release {{ k3s_version }}"
  ansible.builtin.uri:
    url: "https://api.github.com/repos/k3s-io/k3s/releases/tags/{{ k3s_version | urlencode }}"
    return_content: true
    headers:
      Accept: application/vnd.github+json
  register: k3s_release_data

- name: "[DEBUG] Show the GitHub release data for K3s release {{ k3s_version }}"
  ansible.builtin.debug:
    msg: "{{ k3s_release_data.json.assets }}"
    verbosity: 1
