---
- name: Create the directories to host config and output
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/rancher/k3s/config.yaml.d/
    - "{{ k3s_kubeconfig_path }}"

# Agent config options: https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
- name: Template the shared K3s config
  ansible.builtin.template:
    src: templates/config.common.yaml.j2
    dest: /etc/rancher/k3s/config.yaml.d/common.yaml
    backup: true
    force: true
    owner: root
    group: root
    mode: "0600"

# Agent server options: https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
- name: Template the master K3s config
  ansible.builtin.template:
    src: templates/config.master.yaml.j2
    dest: /etc/rancher/k3s/config.yaml.d/master.yaml
    backup: true
    force: true
    owner: root
    group: root
    mode: "0600"
  when: oracle_metadata_instance.definedTags["K3s-NodeInfo"].NodeRole == "master"
# TODO: selectively perform a cluster-init with reset from S3
