---
- hosts: all
  name: Configure and set up a K3s Node
  force_handlers: true
  collections:
    - kube_on_the_cheap.oci_k3s
  roles:
    - node_setup
    - node_facts
    - k3s_setup
    - k3s_start
