---
- name: Gather facts about this instance
  tags:
    - system
    - metadata
  ansible.builtin.import_tasks: facts.yml

- name: "[META] Set the NodeInitStatus as starting"
  tags:
    - metadata
  oracle.oci.oci_compute_instance:
    instance_id: "{{ oracle_metadata_instance.id }}"
    auth_type: instance_principal
    defined_tags: "{{ oracle_metadata_instance.definedTags | ansible.builtin.combine({'K3s-NodeInfo': {'NodeInitStatus': 'starting'}}, recursive=true) }}"
    # WARN: Please please please leave this, otherwise this will try to poll a work_request with a lot more permissions needed
    wait: false
