---
- name: Gather facts about this instance
  tags:
    - system
    - metadata
  ansible.builtin.import_tasks: facts.yml

- name: "[META] Set the NodeInitStatus as starting"
  oracle.oci.oci_compute_instance:
    instance_id: "{{ oracle_metadata_instance.id }}"
    auth_type: instance_principal
    defined_tags:
      K3s-NodeInfo:
        NodeInitStatus: starting
