name: Syntax Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo, all branches, all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Get changed files
        uses: tj-actions/changed-files@v35.9.0
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
